name: Build Minecraft Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: minecraft-plugin
        path: target/*.jar
        if-no-files-found: error
        compression-level: 6
